version: 2.1

references:
  build-checksum-file: &build-checksum-file
    run:
      name: Build checksum file
      command: |
        declare -a FILES=(
          "script/linting/requirements.txt"
          "script/typing/requirements.txt"
        )
        for f in ${FILES[@]}
        do
          echo "# $f" >> all-requirements.txt
          cat $f >> all-requirements.txt
        done

        echo "# self" >> all-requirements.txt
        echo "." >> all-requirements.txt

        declare -a FILES=(
          "setup.py"
          "all-requirements.txt"
        )
        for f in ${FILES[@]}
        do
          echo "# $f" >> .checksum
          cat $f >> .checksum
        done
  restore-dependencies-cache: &restore-dependencies-cache
    restore_cache:
      keys:
        - deps-1-py<< parameters.version >>-{{ checksum ".checksum" }}
  install-dependencies: &install-dependencies
    run:
      name: Install Dependencies
      command: |
        python3 -m venv venv
        venv/bin/pip install -U pip setuptools wheel
        venv/bin/pip install -r all-requirements.txt
  save-dependencies-cache: &save-dependencies-cache
    save_cache:
      key: deps-1-py<< parameters.version >>-{{ checksum ".checksum" }}
      paths:
        - venv
  parametrised-python-executor: &parametrised-python-executor
    parameters:
      version:
        type: string
    executor:
      name: python
      version: << parameters.version >>
  python-full-version-matrix: &python-full-version-matrix
    matrix:
      parameters:
        version: ["3.7", "3.8", "3.9", "3.10"]
  python-top-and-bottom-version-matrix: &python-top-and-bottom-version-matrix
    matrix:
      parameters:
        version: ["3.7", "3.10"]
  filter-tags: &filter-tags
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v.*/


executors:
  python:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/python:<< parameters.version >>

jobs:
  test:
    <<: *parametrised-python-executor

    steps:
      - checkout

      - *build-checksum-file
      - *restore-dependencies-cache
      - *install-dependencies
      - *save-dependencies-cache

      - run:
          name: Run Tests
          command: |
            source venv/bin/activate
            ./script/testing/run-tests

  lint:
    <<: *parametrised-python-executor

    steps:
      - checkout

      - *build-checksum-file
      - *restore-dependencies-cache
      - *install-dependencies
      - *save-dependencies-cache

      - run:
          name: Run Flake8
          command: |
            source venv/bin/activate
            # Ignore TODOs on CI, for now, even though we do want them
            # highlighted in development.
            ./script/linting/lint --extend-ignore=T000

  typecheck:
    <<: *parametrised-python-executor

    steps:
      - checkout

      - *build-checksum-file
      - *restore-dependencies-cache
      - *install-dependencies
      - *save-dependencies-cache

      - run:
          name: Run Mypy
          command: |
            source venv/bin/activate
            ./script/typing/check

  release:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout

      - run:
          name: Setup virtualenv
          command: |
            python3 -m venv venv
            venv/bin/pip install -r script/release/requirements.txt

      - run:
          name: Push to PyPI
          command: |
            source venv/bin/activate
            export TWINE_USERNAME=__token__
            export TWINE_PASSWORD=$PYPI_TOKEN
            ./script/release/release

workflows:
  version: 2.1

  validate:
    jobs:
      - test:
          <<: *python-full-version-matrix
      - lint:
          <<: *python-top-and-bottom-version-matrix
      - typecheck:
          <<: *python-top-and-bottom-version-matrix

  release:
    jobs:
      - test:
          <<: *python-full-version-matrix
          <<: *filter-tags
      - lint:
          <<: *python-top-and-bottom-version-matrix
          <<: *filter-tags
      - typecheck:
          <<: *python-top-and-bottom-version-matrix
          <<: *filter-tags
      - release:
          <<: *filter-tags
          requires:
            - test
            - lint
            - typecheck
